name: gesturetalk1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # 🔽 Tumhari existing dependencies
  cupertino_icons: ^1.0.8
  permission_handler:
  flutter_local_notifications: ^19.1.0
  torch_light: ^1.0.0
  vibration: ^3.1.3
  shared_preferences: ^2.0.15
  supabase_flutter: ^2.8.4
  gradient_borders: ^1.0.0

  # 🔽 Sir wali extra dependencies (newly added)
  bottom_picker: 
  country_code_picker: 
  dropdown_button2: 
  flutter_slidable: 
  gap: ^3.0.1 
  flutter_staggered_grid_view:
  table_calendar: 
  syncfusion_flutter_sliders:
  svg_flutter: 
  google_fonts: 
  get: 
  simple_gradient_text: 
  weekly_date_picker:
  cached_network_image: 
  intl:
  persistent_bottom_nav_bar:
  carousel_slider: 
  pinput: 
  bottom_navy_bar: 
  stylish_bottom_bar: 
  flutter_animate: ^4.5.2
  bounce: ^1.0.2
  intro_screen_onboarding_flutter: ^1.0.0
  smooth_page_indicator: 
  syncfusion_flutter_charts: ^28.1.4
  fl_chart: 
  draggable_home:
  flutter_advanced_drawer: 
  tap_to_expand: ^0.7.2
  persistent_bottom_nav_bar_v2: 
  dotted_border:
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
